[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"
  TZ = "Asia/Shanghai"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
